POST 127.0.0.1:8080/api/teacher/bio-update
Content-Type: application/json
Authorization: d68ee604-58e0-48a4-8921-0db20a74ed42

{
  "bio": "new bio1234"
}

###

GET 127.0.0.1:8080/api/teacher/1
Content-Type: application/json

###

POST 127.0.0.1:8080/api/teacher/new_lesson
Content-Type: application/json
Authorization: 37a54b65-16c2-47bc-9937-97a0497e66ef

{
  "teacherId": 1,
  "date": "2022-05-01T01:01:00Z",
  "price": 500.0,
  "zoomLink": "zoomzoom"
}

###


