POST 127.0.0.1:8080/api/teacher/bio-update
Content-Type: application/json
Authorization: 81b0b764-3ad0-4398-b045-4549ed0f5eb7

{
  "bio": "new bio1234"
}

###

GET 127.0.0.1:8080/api/teacher/1
Content-Type: application/json

###

POST 127.0.0.1:8080/api/teacher/new_lesson
Content-Type: application/json
Authorization: 81b0b764-3ad0-4398-b045-4549ed0f5eb7

{
  "teacherId": 1,
  "date": "2023-01-01T00:00:00Z",
  "price": 500.0,
  "zoomLink": "zoomzoom"
}