### Send POST request with json body
POST 127.0.0.1:8080/api/user/login
Content-Type: application/json

{
  "login": "a",
  "password": "a"
}

###

POST 127.0.0.1:8080/api/user/login
Content-Type: application/json

{
  "login": "Olegych",
  "password": "Password"
}

###

GET 127.0.0.1:8080/api/user/logout
Content-Type: application/json
Authorization: 4243e22a-9a42-4f14-a052-ae6630b483dd

###

GET 127.0.0.1:8080/api/user/logout
Content-Type: application/json
#Authorization: a292a2c2-cd21-4d58-973e-7af65a78c71d

###

POST 127.0.0.1:8080/api/user/create
Content-Type: application/json

{
  "login": "Olegych",
  "firstname": "Aleh",
  "surname": "Aleh",
  "password": "Password",
  "email": "EMAIL",
  "phoneNumber": "1234566711",
  "sex": "Male",
  "userType": "StudentType"
}


###

GET 127.0.0.1:8080/api/user/by-id/123
Content-Type: application/json

###

GET 127.0.0.1:8080/api/user/by-id/1
Content-Type: application/json

###


GET 127.0.0.1:8080/api/user/by-login/Olegych
Content-Type: application/json

###

GET 127.0.0.1:8080/api/user/by-login/12
Content-Type: application/json

###
